from __future__ import annotations

import json
import re
from collections.abc import Mapping
from pathlib import Path
from typing import Any

from meshcall.ir import RequestStyle, ServiceContract, StreamKind, TypeRef


def render_typescript_client(
    contract: ServiceContract,
    *,
    class_name: str | None = None,
    runtime_import: str = "@meshcall/runtime",
    runtime_version: str = "^0.1.0",
) -> str:
    _require_unary(contract, "TypeScript")
    registry = _TypeRegistry(contract)
    lines = [
        "// Generated by MeshCall. Do not edit manually.",
        (
            "// External dependency: "
            f"yarn add {runtime_import}@{runtime_version}"
        ),
        f"import {{ MeshCallClient, type CallOptions }} from {json.dumps(runtime_import)};",
        "",
    ]
    for ref in registry.refs:
        lines.extend(_render_typescript_declarations(registry.name(ref), ref.schema_))
        lines.append("")
    lines.extend(
        _render_client_class(
            contract,
            registry,
            class_name or typescript_client_class_name(contract),
        )
    )
    return "\n".join(lines)


def render_typescript_models(contract: ServiceContract) -> str:
    _require_unary(contract, "TypeScript")
    registry = _TypeRegistry(contract)
    lines = ["// Generated by MeshCall. Do not edit manually.", ""]
    for ref in registry.refs:
        lines.extend(_render_typescript_declarations(registry.name(ref), ref.schema_))
        lines.append("")
    return "\n".join(lines)


def render_typescript_client_module(
    contract: ServiceContract,
    *,
    class_name: str | None = None,
    runtime_import: str = "@meshcall/runtime",
    models_import: str = "./models.js",
) -> str:
    _require_unary(contract, "TypeScript")
    registry = _TypeRegistry(contract)
    type_names = ", ".join(registry.name(ref) for ref in registry.refs)
    lines = [
        "// Generated by MeshCall. Do not edit manually.",
        f"import {{ MeshCallClient, type CallOptions }} from {json.dumps(runtime_import)};",
        f"import type {{ {type_names} }} from {json.dumps(models_import)};",
        "",
    ]
    lines.extend(
        _render_client_class(
            contract,
            registry,
            class_name or typescript_client_class_name(contract),
        )
    )
    return "\n".join(lines)


def typescript_type_names(contract: ServiceContract) -> tuple[str, ...]:
    registry = _TypeRegistry(contract)
    return tuple(registry.name(ref) for ref in registry.refs)


def typescript_client_class_name(contract: ServiceContract) -> str:
    base = contract.source_qualname.rsplit(".", 1)[-1]
    return f"{_identifier(base, fallback='Service')}Client"


def write_typescript_client(
    contract: ServiceContract,
    output: str | Path,
    *,
    class_name: str | None = None,
    runtime_import: str = "@meshcall/runtime",
    runtime_version: str = "^0.1.0",
) -> Path:
    target = Path(output)
    target.parent.mkdir(parents=True, exist_ok=True)
    temporary = target.with_suffix(f"{target.suffix}.tmp")
    temporary.write_text(
        render_typescript_client(
            contract,
            class_name=class_name,
            runtime_import=runtime_import,
            runtime_version=runtime_version,
        ),
        encoding="utf-8",
    )
    temporary.replace(target)
    return target


class _TypeRegistry:
    def __init__(self, contract: ServiceContract) -> None:
        refs: dict[tuple[str, str], TypeRef] = {}
        for method in contract.methods:
            for ref in (
                method.request,
                method.response,
                method.input_item,
                method.output_item,
            ):
                if ref is not None:
                    refs.setdefault((ref.module, ref.qualname), ref)
        self.refs = tuple(refs.values())
        counts: dict[str, int] = {}
        self._names: dict[tuple[str, str], str] = {}
        for ref in self.refs:
            base = _identifier(ref.qualname.rsplit(".", 1)[-1], fallback="Payload")
            count = counts.get(base, 0) + 1
            counts[base] = count
            self._names[(ref.module, ref.qualname)] = (
                base if count == 1 else f"{base}{count}"
            )

    def name(self, ref: TypeRef) -> str:
        return self._names[(ref.module, ref.qualname)]


def _render_client_class(
    contract: ServiceContract,
    registry: _TypeRegistry,
    class_name: str,
) -> list[str]:
    lines = [
        f"export class {class_name} {{",
        "  public constructor(private readonly rpc: MeshCallClient) {}",
    ]
    for method in contract.methods:
        request = registry.name(method.request)
        response = registry.name(_required_ref(method.response))
        if method.request_style is RequestStyle.EXPANDED:
            parameters = _expanded_typescript_parameters(method, registry)
            payload = _expanded_typescript_payload(method)
            lines.extend(
                [
                    "",
                    f"  public {method.name}(",
                    *[f"    {parameter}," for parameter in parameters],
                    "    options?: CallOptions,",
                    f"  ): Promise<{response}> {{",
                    f"    return this.rpc.unary<{request}, {response}>(",
                    f"      {json.dumps(contract.name)},",
                    f"      {json.dumps(method.name)},",
                    *payload,
                    "      options,",
                    "    );",
                    "  }",
                ]
            )
        else:
            lines.extend(
                [
                    "",
                    f"  public {method.name}(",
                    f"    request: {request},",
                    "    options?: CallOptions,",
                    f"  ): Promise<{response}> {{",
                    f"    return this.rpc.unary<{request}, {response}>(",
                    f"      {json.dumps(contract.name)},",
                    f"      {json.dumps(method.name)},",
                    "      request,",
                    "      options,",
                    "    );",
                    "  }",
                ]
            )
    lines.extend(["}", ""])
    return lines


def _expanded_typescript_parameters(
    method: Any,
    registry: _TypeRegistry,
) -> list[str]:
    schema = method.request.schema_
    properties = schema.get("properties", {})
    required = set(schema.get("required", []))
    definitions = schema.get("$defs", {})
    root_name = registry.name(method.request)
    definition_names = {
        key: f"{root_name}{_identifier(key, fallback='Value')}"
        for key in definitions
    }
    parameters: list[str] = []
    for field_name in method.request_fields:
        if not re.fullmatch(r"[A-Za-z_$][A-Za-z0-9_$]*", field_name):
            raise TypeError(
                f"Expanded request field {field_name!r} is not a valid "
                "TypeScript parameter name"
            )
        property_schema = properties.get(field_name)
        if not isinstance(property_schema, Mapping):
            raise TypeError(
                f"Expanded request field {field_name!r} is missing from "
                f"{method.request.qualname}"
            )
        field_type = _typescript_type(property_schema, definition_names)
        if field_name in required:
            parameters.append(f"{field_name}: {field_type}")
        elif "default" in property_schema:
            parameters.append(
                f"{field_name}: {field_type} = "
                f"{json.dumps(property_schema['default'])}"
            )
        else:
            parameters.append(f"{field_name}?: {field_type}")
    return parameters


def _expanded_typescript_payload(method: Any) -> list[str]:
    if not method.request_fields:
        return ["      {},"]
    return [
        "      {",
        *[
            f"        {_typescript_property(field_name)}: {field_name},"
            for field_name in method.request_fields
        ],
        "      },",
    ]


def _render_typescript_declarations(
    root_name: str,
    schema: Mapping[str, Any],
) -> list[str]:
    definitions = schema.get("$defs", {})
    definition_names = {
        key: f"{root_name}{_identifier(key, fallback='Value')}"
        for key in definitions
    }
    lines: list[str] = []
    for key, definition in definitions.items():
        lines.extend(
            _render_typescript_declaration(
                definition_names[key],
                definition,
                definition_names,
            )
        )
        lines.append("")
    lines.extend(_render_typescript_declaration(root_name, schema, definition_names))
    return lines


def _render_typescript_declaration(
    name: str,
    schema: Mapping[str, Any],
    definition_names: Mapping[str, str],
) -> list[str]:
    if schema.get("type") == "object" or "properties" in schema:
        required = set(schema.get("required", []))
        lines = [f"export interface {name} {{"]
        for property_name, property_schema in schema.get("properties", {}).items():
            rendered_name = _typescript_property(property_name)
            optional = "" if property_name in required else "?"
            rendered_type = _typescript_type(property_schema, definition_names)
            lines.append(f"  {rendered_name}{optional}: {rendered_type};")
        additional = schema.get("additionalProperties")
        if additional is True:
            lines.append("  [key: string]: unknown;")
        elif isinstance(additional, Mapping):
            value_type = _typescript_type(additional, definition_names)
            lines.append(f"  [key: string]: {value_type};")
        lines.append("}")
        return lines
    return [f"export type {name} = {_typescript_type(schema, definition_names)};"]


def _typescript_type(
    schema: Mapping[str, Any],
    definition_names: Mapping[str, str],
) -> str:
    reference = schema.get("$ref")
    if isinstance(reference, str) and reference.startswith("#/$defs/"):
        key = reference.rsplit("/", 1)[-1]
        return definition_names.get(key, _identifier(key, fallback="unknown"))
    if "const" in schema:
        return json.dumps(schema["const"])
    enum = schema.get("enum")
    if isinstance(enum, list) and enum:
        return " | ".join(json.dumps(value) for value in enum)
    for keyword in ("anyOf", "oneOf"):
        variants = schema.get(keyword)
        if isinstance(variants, list) and variants:
            return " | ".join(
                _typescript_type(variant, definition_names) for variant in variants
            )
    all_of = schema.get("allOf")
    if isinstance(all_of, list) and all_of:
        return " & ".join(
            _typescript_type(variant, definition_names) for variant in all_of
        )
    schema_type = schema.get("type")
    if isinstance(schema_type, list):
        return " | ".join(
            _typescript_type({**schema, "type": item}, definition_names)
            for item in schema_type
        )
    if schema_type in ("integer", "number"):
        return "number"
    if schema_type == "string":
        return "string"
    if schema_type == "boolean":
        return "boolean"
    if schema_type == "null":
        return "null"
    if schema_type == "array":
        item_type = _typescript_type(schema.get("items", {}), definition_names)
        return f"Array<{item_type}>"
    if schema_type == "object":
        additional = schema.get("additionalProperties", {})
        value_type = (
            _typescript_type(additional, definition_names)
            if isinstance(additional, Mapping)
            else "unknown"
        )
        return f"Record<string, {value_type}>"
    return "unknown"


def _typescript_property(name: str) -> str:
    return name if re.fullmatch(r"[A-Za-z_$][A-Za-z0-9_$]*", name) else json.dumps(name)


def _identifier(value: str, *, fallback: str) -> str:
    identifier = re.sub(r"[^A-Za-z0-9_$]", "_", value)
    if not identifier:
        return fallback
    if identifier[0].isdigit():
        return f"_{identifier}"
    return identifier


def _required_ref(ref: TypeRef | None) -> TypeRef:
    if ref is None:
        raise ValueError("Unary method is missing a response type")
    return ref


def _require_unary(contract: ServiceContract, target: str) -> None:
    unsupported = [
        method.name for method in contract.methods if method.stream is not StreamKind.UNARY
    ]
    if unsupported:
        names = ", ".join(unsupported)
        raise ValueError(f"{target} generation currently supports unary methods only: {names}")
