from __future__ import annotations

import keyword
import re
from collections.abc import Mapping
from pathlib import Path
from typing import Any

from meshcall.ir import RequestStyle, ServiceContract, StreamKind, TypeRef


def render_portable_python_client(
    contract: ServiceContract,
    *,
    class_name: str | None = None,
    meshcall_requirement: str = "meshcall>=0.1.0",
    pydantic_requirement: str = "pydantic>=2.11",
) -> str:
    registry = _TypeRegistry(contract)
    model_lines = _render_model_declarations(registry)
    lines = [
        "# Generated by MeshCall from a portable contract. Do not edit manually.",
        (
            "# External dependencies: "
            f"uv add {meshcall_requirement!r} {pydantic_requirement!r}"
        ),
        "from __future__ import annotations",
    ]
    if any(method.stream is StreamKind.CLIENT for method in contract.methods):
        lines.extend(["", "from collections.abc import AsyncIterable"])
    lines.extend(_model_import_lines(model_lines))
    lines.extend(["", "from meshcall.client import ClientBase"])
    stream_imports = _stream_imports(contract)
    if stream_imports:
        lines.append(f"from meshcall.streams import {', '.join(stream_imports)}")
    lines.extend(["", ""])
    lines.extend(model_lines)
    lines.extend(["", ""])
    lines.extend(
        _render_client_class(
            contract,
            registry,
            class_name or portable_python_client_class_name(contract),
        )
    )
    return "\n".join(lines) + "\n"


def render_portable_python_models(contract: ServiceContract) -> str:
    registry = _TypeRegistry(contract)
    model_lines = _render_model_declarations(registry)
    lines = [
        "# Generated by MeshCall from a portable contract. Do not edit manually.",
        "from __future__ import annotations",
    ]
    lines.extend(_model_import_lines(model_lines))
    lines.extend(["", ""])
    lines.extend(model_lines)
    return "\n".join(lines).rstrip() + "\n"


def render_portable_python_client_module(
    contract: ServiceContract,
    *,
    class_name: str | None = None,
    models_import: str = ".models",
) -> str:
    registry = _TypeRegistry(contract)
    type_names = ", ".join(registry.name(ref) for ref in registry.refs)
    lines = [
        "# Generated by MeshCall from a portable contract. Do not edit manually.",
        "from __future__ import annotations",
    ]
    if any(method.stream is StreamKind.CLIENT for method in contract.methods):
        lines.extend(["", "from collections.abc import AsyncIterable"])
    lines.extend(["", "from meshcall.client import ClientBase"])
    stream_imports = _stream_imports(contract)
    if stream_imports:
        lines.append(f"from meshcall.streams import {', '.join(stream_imports)}")
    lines.extend(["", f"from {models_import} import {type_names}", "", ""])
    lines.extend(
        _render_client_class(
            contract,
            registry,
            class_name or portable_python_client_class_name(contract),
        )
    )
    return "\n".join(lines) + "\n"


def portable_python_type_names(contract: ServiceContract) -> tuple[str, ...]:
    registry = _TypeRegistry(contract)
    return tuple(registry.name(ref) for ref in registry.refs)


def portable_python_client_class_name(contract: ServiceContract) -> str:
    base = contract.source_qualname.rsplit(".", 1)[-1]
    return f"{_class_name(base, fallback='Service')}Client"


def write_portable_python_client(
    contract: ServiceContract,
    output: str | Path,
    *,
    class_name: str | None = None,
    meshcall_requirement: str = "meshcall>=0.1.0",
    pydantic_requirement: str = "pydantic>=2.11",
) -> Path:
    target = Path(output)
    target.parent.mkdir(parents=True, exist_ok=True)
    temporary = target.with_suffix(f"{target.suffix}.tmp")
    temporary.write_text(
        render_portable_python_client(
            contract,
            class_name=class_name,
            meshcall_requirement=meshcall_requirement,
            pydantic_requirement=pydantic_requirement,
        ),
        encoding="utf-8",
    )
    temporary.replace(target)
    return target


class _TypeRegistry:
    def __init__(self, contract: ServiceContract) -> None:
        refs: dict[tuple[str, str], TypeRef] = {}
        for method in contract.methods:
            for ref in (
                method.request,
                method.response,
                method.input_item,
                method.output_item,
            ):
                if ref is not None:
                    refs.setdefault((ref.module, ref.qualname), ref)
        self.refs = tuple(refs.values())
        counts: dict[str, int] = {}
        self._names: dict[tuple[str, str], str] = {}
        for ref in self.refs:
            base = _class_name(ref.qualname.rsplit(".", 1)[-1], fallback="Payload")
            count = counts.get(base, 0) + 1
            counts[base] = count
            self._names[(ref.module, ref.qualname)] = (
                base if count == 1 else f"{base}{count}"
            )

    def name(self, ref: TypeRef) -> str:
        return self._names[(ref.module, ref.qualname)]


def _render_client_class(
    contract: ServiceContract,
    registry: _TypeRegistry,
    class_name: str,
) -> list[str]:
    lines = [
        f"class {class_name}(ClientBase):",
        f"    service_name = {contract.name!r}",
    ]
    for method in contract.methods:
        request = registry.name(method.request)
        expanded = method.request_style is RequestStyle.EXPANDED
        request_parameters = (
            _expanded_python_parameters(method, registry)
            if expanded
            else [f"request: {request}"]
        )
        lines.append("")
        if method.stream is StreamKind.UNARY:
            response = registry.name(_required_ref(method.response))
            lines.extend(
                [
                    f"    async def {method.name}(",
                    "        self,",
                    *[f"        {parameter}," for parameter in request_parameters],
                    "        *,",
                    "        timeout: float | None = None,",
                    f"    ) -> {response}:",
                    *(_expanded_request_lines(method, request) if expanded else []),
                    "        return await self._unary(",
                    "            self.service_name,",
                    f"            {method.name!r},",
                    "            request,",
                    f"            {response},",
                    "            timeout=timeout,",
                    "        )",
                ]
            )
        elif method.stream is StreamKind.SERVER:
            output = registry.name(_required_ref(method.output_item))
            lines.extend(
                [
                    f"    def {method.name}(",
                    "        self,",
                    *[f"        {parameter}," for parameter in request_parameters],
                    "        *,",
                    "        timeout: float | None = None,",
                    f"    ) -> RpcServerStream[{output}]:",
                    *(_expanded_request_lines(method, request) if expanded else []),
                    "        return self._server_stream(",
                    "            self.service_name,",
                    f"            {method.name!r},",
                    "            request,",
                    f"            {output},",
                    "            timeout=timeout,",
                    "        )",
                ]
            )
        elif method.stream is StreamKind.CLIENT:
            input_item = registry.name(_required_ref(method.input_item))
            response = registry.name(_required_ref(method.response))
            lines.extend(
                [
                    f"    async def {method.name}(",
                    "        self,",
                    *[f"        {parameter}," for parameter in request_parameters],
                    f"        items: AsyncIterable[{input_item}],",
                    "        *,",
                    "        timeout: float | None = None,",
                    f"    ) -> {response}:",
                    *(_expanded_request_lines(method, request) if expanded else []),
                    "        return await self._client_stream(",
                    "            self.service_name,",
                    f"            {method.name!r},",
                    "            request,",
                    "            items,",
                    f"            {input_item},",
                    f"            {response},",
                    "            timeout=timeout,",
                    "        )",
                ]
            )
        else:
            input_item = registry.name(_required_ref(method.input_item))
            output_item = registry.name(_required_ref(method.output_item))
            result = (
                registry.name(method.response)
                if method.response is not None
                else "None"
            )
            lines.extend(
                [
                    f"    def {method.name}(",
                    "        self,",
                    *[f"        {parameter}," for parameter in request_parameters],
                    "        *,",
                    "        timeout: float | None = None,",
                    (
                        "    ) -> "
                        f"RpcDuplexClient[{input_item}, {output_item}, {result}]:"
                    ),
                    *(_expanded_request_lines(method, request) if expanded else []),
                    "        return self._duplex(",
                    "            self.service_name,",
                    f"            {method.name!r},",
                    "            request,",
                    f"            {input_item},",
                    f"            {output_item},",
                    f"            {result},",
                    "            timeout=timeout,",
                    "        )",
                ]
            )
    return lines


def _expanded_python_parameters(
    method: Any,
    registry: _TypeRegistry,
) -> list[str]:
    schema = method.request.schema_
    properties = schema.get("properties", {})
    required = set(schema.get("required", []))
    definitions = schema.get("$defs", {})
    root_name = registry.name(method.request)
    definition_names = {
        key: f"{root_name}{_class_name(key, fallback='Value')}"
        for key in definitions
    }
    parameters: list[str] = []
    for field_name in method.request_fields:
        property_schema = properties.get(field_name)
        if not isinstance(property_schema, Mapping):
            raise TypeError(
                f"Expanded request field {field_name!r} is missing from "
                f"{method.request.qualname}"
            )
        field_type = _python_type(property_schema, definition_names)
        if field_name in required:
            parameters.append(f"{field_name}: {field_type}")
        elif "default" in property_schema:
            parameters.append(
                f"{field_name}: {field_type} = {property_schema['default']!r}"
            )
        else:
            parameters.append(f"{field_name}: {field_type} | None = None")
    return parameters


def _expanded_request_lines(method: Any, request_name: str) -> list[str]:
    if not method.request_fields:
        return [f"        request = {request_name}()"]
    return [
        f"        request = {request_name}(",
        *[f"            {field_name}={field_name}," for field_name in method.request_fields],
        "        )",
    ]


def _stream_imports(contract: ServiceContract) -> list[str]:
    imports: list[str] = []
    if any(method.stream is StreamKind.DUPLEX for method in contract.methods):
        imports.append("RpcDuplexClient")
    if any(method.stream is StreamKind.SERVER for method in contract.methods):
        imports.append("RpcServerStream")
    return imports


def _render_model_declarations(registry: _TypeRegistry) -> list[str]:
    lines: list[str] = []
    for ref in registry.refs:
        if lines:
            lines.extend(["", ""])
        lines.extend(_render_python_models(registry.name(ref), ref.schema_))
    return lines


def _model_import_lines(model_lines: list[str]) -> list[str]:
    typing_imports = [
        name
        for name in ("Any", "Literal")
        if any(re.search(rf"\b{name}\b", line) for line in model_lines)
    ]
    pydantic_imports = ["BaseModel"]
    if any("Field(" in line for line in model_lines):
        pydantic_imports.append("Field")

    lines: list[str] = []
    if typing_imports:
        lines.extend(["", f"from typing import {', '.join(typing_imports)}"])
    lines.extend(["", f"from pydantic import {', '.join(pydantic_imports)}"])
    return lines


def _render_python_models(
    root_name: str,
    schema: Mapping[str, Any],
) -> list[str]:
    definitions = schema.get("$defs", {})
    definition_names = {
        key: f"{root_name}{_class_name(key, fallback='Value')}"
        for key in definitions
    }
    lines: list[str] = []
    for key, definition in definitions.items():
        lines.extend(_render_python_model(definition_names[key], definition, definition_names))
        lines.extend(["", ""])
    lines.extend(_render_python_model(root_name, schema, definition_names))
    return lines


def _render_python_model(
    name: str,
    schema: Mapping[str, Any],
    definition_names: Mapping[str, str],
) -> list[str]:
    if "enum" in schema or "const" in schema:
        return [f"{name} = {_python_type(schema, definition_names)}"]
    if schema.get("type") != "object" and "properties" not in schema:
        raise ValueError(f"Portable Python model {name} must use an object schema")
    required = set(schema.get("required", []))
    properties = schema.get("properties", {})
    lines = [f"class {name}(BaseModel):"]
    if not properties:
        lines.append("    pass")
        return lines
    for property_name, property_schema in properties.items():
        field_name = _field_name(property_name)
        field_type = _python_type(property_schema, definition_names)
        is_required = property_name in required
        if not is_required and "default" not in property_schema:
            field_type = f"{field_type} | None"
        default = ""
        if not is_required:
            default_value = property_schema.get("default", None)
            default = f" = {default_value!r}"
        if field_name != property_name:
            field_options = f"alias={property_name!r}"
            field_default = "..." if is_required else repr(property_schema.get("default"))
            default = f" = Field({field_default}, {field_options})"
        lines.append(f"    {field_name}: {field_type}{default}")
    return lines


def _python_type(
    schema: Mapping[str, Any],
    definition_names: Mapping[str, str],
) -> str:
    reference = schema.get("$ref")
    if isinstance(reference, str) and reference.startswith("#/$defs/"):
        key = reference.rsplit("/", 1)[-1]
        return definition_names.get(key, _class_name(key, fallback="Any"))
    if "const" in schema:
        return f"Literal[{schema['const']!r}]"
    enum = schema.get("enum")
    if isinstance(enum, list) and enum:
        values = ", ".join(repr(value) for value in enum)
        return f"Literal[{values}]"
    for keyword_name in ("anyOf", "oneOf"):
        variants = schema.get(keyword_name)
        if isinstance(variants, list) and variants:
            return " | ".join(
                _python_type(variant, definition_names) for variant in variants
            )
    schema_type = schema.get("type")
    if isinstance(schema_type, list):
        return " | ".join(
            _python_type({**schema, "type": item}, definition_names)
            for item in schema_type
        )
    if schema_type == "integer":
        return "int"
    if schema_type == "number":
        return "float"
    if schema_type == "string":
        return "str"
    if schema_type == "boolean":
        return "bool"
    if schema_type == "null":
        return "None"
    if schema_type == "array":
        return f"list[{_python_type(schema.get('items', {}), definition_names)}]"
    if schema_type == "object":
        additional = schema.get("additionalProperties", {})
        value_type = (
            _python_type(additional, definition_names)
            if isinstance(additional, Mapping)
            else "Any"
        )
        return f"dict[str, {value_type}]"
    return "Any"


def _field_name(value: str) -> str:
    identifier = re.sub(r"\W", "_", value)
    if not identifier or identifier[0].isdigit():
        identifier = f"field_{identifier}"
    if keyword.iskeyword(identifier):
        identifier = f"{identifier}_"
    return identifier


def _class_name(value: str, *, fallback: str) -> str:
    identifier = re.sub(r"[^A-Za-z0-9_]", "_", value)
    if not identifier:
        return fallback
    if identifier[0].isdigit():
        return f"Model_{identifier}"
    return identifier


def _required_ref(ref: TypeRef | None) -> TypeRef:
    if ref is None:
        raise ValueError("RPC method is missing a required payload type")
    return ref
