# Generated by MeshCall from a portable contract. Do not edit manually.
# External dependencies: uv add 'meshcall>=0.1.0' 'pydantic>=2.11'
from __future__ import annotations

from pydantic import BaseModel

from meshcall.client import ClientBase
from meshcall.streams import RpcServerStream


class CounterServiceCountRequest(BaseModel):
    stop: int


class CountItem(BaseModel):
    value: int


class CounterServiceClient(ClientBase):
    service_name = 'example.v1.CounterService'

    def count(
        self,
        stop: int,
        *,
        timeout: float | None = None,
    ) -> RpcServerStream[CountItem]:
        request = CounterServiceCountRequest(
            stop=stop,
        )
        return self._server_stream(
            self.service_name,
            'count',
            request,
            CountItem,
            timeout=timeout,
        )
