// Generated by MeshCall. Do not edit manually.
import { MeshCallClient, type CallOptions, type MeshCallServerStream } from "@meshcall/runtime";
import type { LlmServiceNewSessionRequest, NewSessionResponse, LlmServiceListSessionsRequest, ListSessionsResponse, LlmServiceCountTokensRequest, TokenCountResponse, LlmServiceAssemblePromptRequest, PromptAssembly, PromptChunk, LlmServiceStreamChatRequest, ChatChunk } from "./models.js";

export class LlmServiceClient {
  public constructor(private readonly rpc: MeshCallClient) {}

  public new_session(
    title: string = "New session",
    options?: CallOptions,
  ): Promise<NewSessionResponse> {
    return this.rpc.unary<LlmServiceNewSessionRequest, NewSessionResponse>(
      "best_practice.v1.LlmService",
      "new_session",
      {
        title: title,
      },
      options,
    );
  }

  public list_sessions(
    options?: CallOptions,
  ): Promise<ListSessionsResponse> {
    return this.rpc.unary<LlmServiceListSessionsRequest, ListSessionsResponse>(
      "best_practice.v1.LlmService",
      "list_sessions",
      {},
      options,
    );
  }

  public count_tokens(
    text: string,
    options?: CallOptions,
  ): Promise<TokenCountResponse> {
    return this.rpc.unary<LlmServiceCountTokensRequest, TokenCountResponse>(
      "best_practice.v1.LlmService",
      "count_tokens",
      {
        text: text,
      },
      options,
    );
  }

  public assemble_prompt(
    items: AsyncIterable<PromptChunk>,
    options?: CallOptions,
  ): Promise<PromptAssembly> {
    return this.rpc.clientStream<LlmServiceAssemblePromptRequest, PromptChunk, PromptAssembly>(
      "best_practice.v1.LlmService",
      "assemble_prompt",
      {},
      items,
      options,
    );
  }

  public stream_chat(
    session_id: string,
    prompt: string,
    max_tokens: number = 64,
    options?: CallOptions,
  ): MeshCallServerStream<ChatChunk> {
    return this.rpc.serverStream<LlmServiceStreamChatRequest, ChatChunk>(
      "best_practice.v1.LlmService",
      "stream_chat",
      {
        session_id: session_id,
        prompt: prompt,
        max_tokens: max_tokens,
      },
      options,
    );
  }
}
