// Generated by MeshCall. Do not edit manually.

export interface LlmServiceNewSessionRequest {
  title?: string;
}

export interface NewSessionResponseSessionInfo {
  id: string;
  title: string;
  message_count: number;
}

export interface NewSessionResponse {
  session: NewSessionResponseSessionInfo;
}

export interface LlmServiceListSessionsRequest {
}

export interface ListSessionsResponseSessionInfo {
  id: string;
  title: string;
  message_count: number;
}

export interface ListSessionsResponse {
  sessions: Array<ListSessionsResponseSessionInfo>;
}

export interface LlmServiceCountTokensRequest {
  text: string;
}

export interface TokenCountResponse {
  count: number;
  tokenizer: string;
}

export interface LlmServiceAssemblePromptRequest {
}

export interface PromptAssembly {
  text: string;
  chunk_count: number;
}

export interface PromptChunk {
  text: string;
}

export interface LlmServiceStreamChatRequest {
  session_id: string;
  prompt: string;
  max_tokens?: number;
}

export interface ChatChunk {
  delta: string;
  index: number;
}
