# Generated by MeshCall from a portable contract. Do not edit manually.
from __future__ import annotations

from meshcall.client import ClientBase

from .models import GreetingRequest, GreetingResult


class TypeScriptGreetingServiceClient(ClientBase):
    service_name = 'demo.v1.TypeScriptGreetingService'

    async def greet(
        self,
        request: GreetingRequest,
        *,
        timeout: float | None = None,
    ) -> GreetingResult:
        return await self._unary(
            self.service_name,
            'greet',
            request,
            GreetingResult,
            timeout=timeout,
        )
