# Generated by MeshCall from a portable contract. Do not edit manually.
from __future__ import annotations

from collections.abc import AsyncIterable

from meshcall.client import ClientBase
from meshcall.streams import RpcServerStream

from .models import (
    CountRequest,
    GreetingRequest,
    GreetingResult,
    NumberItem,
    SumRequest,
    SumResult,
)


class TypeScriptGreetingServiceClient(ClientBase):
    service_name = 'demo.v1.TypeScriptGreetingService'

    def count(
        self,
        request: CountRequest,
        *,
        timeout: float | None = None,
    ) -> RpcServerStream[NumberItem]:
        return self._server_stream(
            self.service_name,
            'count',
            request,
            NumberItem,
            timeout=timeout,
        )

    async def sum(
        self,
        request: SumRequest,
        items: AsyncIterable[NumberItem],
        *,
        timeout: float | None = None,
    ) -> SumResult:
        return await self._client_stream(
            self.service_name,
            'sum',
            request,
            items,
            NumberItem,
            SumResult,
            timeout=timeout,
        )

    async def greet(
        self,
        request: GreetingRequest,
        *,
        timeout: float | None = None,
    ) -> GreetingResult:
        return await self._unary(
            self.service_name,
            'greet',
            request,
            GreetingResult,
            timeout=timeout,
        )
