# Generated by MeshCall from a portable contract. Do not edit manually.
from __future__ import annotations

from pydantic import BaseModel


class GreetingRequest(BaseModel):
    name: str
    repeat: int


class GreetingResult(BaseModel):
    message: str
    handled_by: str
