# Generated by MeshCall from a portable contract. Do not edit manually.
from __future__ import annotations

from pydantic import BaseModel


class CountRequest(BaseModel):
    count: int


class NumberItem(BaseModel):
    value: int


class SumRequest(BaseModel):
    offset: int = 0


class SumResult(BaseModel):
    total: int


class GreetingRequest(BaseModel):
    name: str
    repeat: int


class GreetingResult(BaseModel):
    message: str
    handled_by: str
