# Generated by MeshCall from a portable contract. Do not edit manually.
# External dependencies: uv add 'meshcall>=0.1.0' 'pydantic>=2.11'
from __future__ import annotations

from collections.abc import AsyncIterable

from pydantic import BaseModel

from meshcall.client import ClientBase
from meshcall.streams import RpcDuplexClient, RpcServerStream


class ShowcaseServiceGreetRequest(BaseModel):
    name: str
    repeat: int = 1


class GreetingResult(BaseModel):
    message: str
    repeat: int


class WelcomeRequest(BaseModel):
    name: str
    tags: list[str]


class WelcomeResult(BaseModel):
    message: str
    tags: list[str]


class ShowcaseServiceCountRequest(BaseModel):
    start: int
    stop: int


class CountItem(BaseModel):
    value: int


class ShowcaseServiceSumValuesRequest(BaseModel):
    offset: int


class TotalResult(BaseModel):
    total: int


class NumberItem(BaseModel):
    value: int


class ShowcaseServiceEchoRequest(BaseModel):
    label: str


class EchoSummary(BaseModel):
    count: int
    total: int


class EchoItem(BaseModel):
    value: int
    label: str


class ShowcaseServiceClient(ClientBase):
    service_name = 'demo.v1.ShowcaseService'

    async def greet(
        self,
        name: str,
        repeat: int = 1,
        *,
        timeout: float | None = None,
    ) -> GreetingResult:
        request = ShowcaseServiceGreetRequest(
            name=name,
            repeat=repeat,
        )
        return await self._unary(
            self.service_name,
            'greet',
            request,
            GreetingResult,
            timeout=timeout,
        )

    async def welcome(
        self,
        request: WelcomeRequest,
        *,
        timeout: float | None = None,
    ) -> WelcomeResult:
        return await self._unary(
            self.service_name,
            'welcome',
            request,
            WelcomeResult,
            timeout=timeout,
        )

    def count(
        self,
        start: int,
        stop: int,
        *,
        timeout: float | None = None,
    ) -> RpcServerStream[CountItem]:
        request = ShowcaseServiceCountRequest(
            start=start,
            stop=stop,
        )
        return self._server_stream(
            self.service_name,
            'count',
            request,
            CountItem,
            timeout=timeout,
        )

    async def sum_values(
        self,
        offset: int,
        items: AsyncIterable[NumberItem],
        *,
        timeout: float | None = None,
    ) -> TotalResult:
        request = ShowcaseServiceSumValuesRequest(
            offset=offset,
        )
        return await self._client_stream(
            self.service_name,
            'sum_values',
            request,
            items,
            NumberItem,
            TotalResult,
            timeout=timeout,
        )

    def echo(
        self,
        label: str,
        *,
        timeout: float | None = None,
    ) -> RpcDuplexClient[NumberItem, EchoItem, EchoSummary]:
        request = ShowcaseServiceEchoRequest(
            label=label,
        )
        return self._duplex(
            self.service_name,
            'echo',
            request,
            NumberItem,
            EchoItem,
            EchoSummary,
            timeout=timeout,
        )
