# Generated by MeshCall. Do not edit manually.
from __future__ import annotations

import examples.service as _types_0
from meshcall.client import ClientBase
from meshcall.streams import RpcServerStream


class CounterServiceClient(ClientBase):
    service_name = 'example.v1.CounterService'

    def count(
        self,
        request: _types_0.CountRequest,
        *,
        timeout: float | None = None,
    ) -> RpcServerStream[_types_0.CountItem]:
        return self._server_stream(
            self.service_name,
            'count',
            request,
            _types_0.CountItem,
            timeout=timeout,
        )
