// Generated by MeshCall. Do not edit manually.
import { MeshCallClient, type CallOptions } from "@meshcall/runtime";
import type { PythonGreetingServiceGreetRequest, GreetingResult } from "./models.js";

export class PythonGreetingServiceClient {
  public constructor(private readonly rpc: MeshCallClient) {}

  public greet(
    name: string,
    repeat: number = 1,
    options?: CallOptions,
  ): Promise<GreetingResult> {
    return this.rpc.unary<PythonGreetingServiceGreetRequest, GreetingResult>(
      "demo.v1.PythonGreetingService",
      "greet",
      {
        name: name,
        repeat: repeat,
      },
      options,
    );
  }
}
