// Generated by MeshCall. Do not edit manually.

export interface PythonGreetingServiceGreetRequest {
  name: string;
  repeat?: number;
}

export interface GreetingResult {
  message: string;
  handled_by: string;
}
