from __future__ import annotations

import re
from pathlib import Path

from meshcall.ir import MethodContract, ServiceContract, StreamKind, TypeRef


def render_client(
    contract: ServiceContract,
    *,
    class_name: str | None = None,
    meshcall_requirement: str = "meshcall>=0.1.0",
) -> str:
    generated_name = class_name or _client_class_name(contract)
    modules = _collect_modules(contract)
    aliases = {module: f"_types_{index}" for index, module in enumerate(modules)}

    lines = [
        "# Generated by MeshCall. Do not edit manually.",
        f"# External dependency: uv add {meshcall_requirement!r}",
        "# The referenced application model modules must also be importable.",
        "from __future__ import annotations",
    ]
    if any(method.stream is StreamKind.CLIENT for method in contract.methods):
        lines.extend(["", "from collections.abc import AsyncIterable"])
    lines.append("")
    for module in modules:
        lines.append(f"import {module} as {aliases[module]}")
    lines.append("from meshcall.client import ClientBase")
    stream_imports: list[str] = []
    if any(method.stream is StreamKind.DUPLEX for method in contract.methods):
        stream_imports.append("RpcDuplexClient")
    if any(method.stream is StreamKind.SERVER for method in contract.methods):
        stream_imports.append("RpcServerStream")
    if stream_imports:
        lines.append(
            f"from meshcall.streams import {', '.join(stream_imports)}"
        )

    lines.extend(
        [
            "",
            "",
            f"class {generated_name}(ClientBase):",
            f"    service_name = {contract.name!r}",
        ]
    )

    for method in contract.methods:
        lines.extend(["", *_render_method(method, contract.name, aliases)])

    return "\n".join(lines) + "\n"


def write_client(
    contract: ServiceContract,
    output: str | Path,
    *,
    class_name: str | None = None,
    meshcall_requirement: str = "meshcall>=0.1.0",
) -> Path:
    target = Path(output)
    target.parent.mkdir(parents=True, exist_ok=True)
    temporary = target.with_suffix(f"{target.suffix}.tmp")
    temporary.write_text(
        render_client(
            contract,
            class_name=class_name,
            meshcall_requirement=meshcall_requirement,
        ),
        encoding="utf-8",
    )
    temporary.replace(target)
    return target


def _render_method(
    method: MethodContract,
    service_name: str,
    aliases: dict[str, str],
) -> list[str]:
    request = _render_type(method.request, aliases)
    prefix = [
        f"    async def {method.name}(" if method.stream in (StreamKind.UNARY, StreamKind.CLIENT) else f"    def {method.name}(",
        "        self,",
        f"        request: {request},",
    ]

    if method.stream is StreamKind.UNARY:
        response = _required_type(method.response, aliases)
        prefix.extend(
            [
                "        *,",
                "        timeout: float | None = None,",
                f"    ) -> {response}:",
                "        return await self._unary(",
                "            self.service_name,",
                f"            {method.name!r},",
                "            request,",
                f"            {response},",
                "            timeout=timeout,",
                "        )",
            ]
        )
        return prefix

    if method.stream is StreamKind.SERVER:
        output = _required_type(method.output_item, aliases)
        prefix.extend(
            [
                "        *,",
                "        timeout: float | None = None,",
                f"    ) -> RpcServerStream[{output}]:",
                "        return self._server_stream(",
                "            self.service_name,",
                f"            {method.name!r},",
                "            request,",
                f"            {output},",
                "            timeout=timeout,",
                "        )",
            ]
        )
        return prefix

    if method.stream is StreamKind.CLIENT:
        input_item = _required_type(method.input_item, aliases)
        response = _required_type(method.response, aliases)
        prefix.extend(
            [
                f"        items: AsyncIterable[{input_item}],",
                "        *,",
                "        timeout: float | None = None,",
                f"    ) -> {response}:",
                "        return await self._client_stream(",
                "            self.service_name,",
                f"            {method.name!r},",
                "            request,",
                "            items,",
                f"            {input_item},",
                f"            {response},",
                "            timeout=timeout,",
                "        )",
            ]
        )
        return prefix

    input_item = _required_type(method.input_item, aliases)
    output_item = _required_type(method.output_item, aliases)
    result = _render_type(method.response, aliases) if method.response else "None"
    result_generic = result if method.response else "None"
    prefix.extend(
        [
            "        *,",
            "        timeout: float | None = None,",
            f"    ) -> RpcDuplexClient[{input_item}, {output_item}, {result_generic}]:",
            "        return self._duplex(",
            "            self.service_name,",
            f"            {method.name!r},",
            "            request,",
            f"            {input_item},",
            f"            {output_item},",
            f"            {result},",
            "            timeout=timeout,",
            "        )",
        ]
    )
    return prefix


def _client_class_name(contract: ServiceContract) -> str:
    base = contract.source_qualname.rsplit(".", 1)[-1]
    name = re.sub(r"[^A-Za-z0-9_]", "_", base)
    if not name or name[0].isdigit():
        name = f"Service_{name}"
    return f"{name}Client"


def _collect_modules(contract: ServiceContract) -> list[str]:
    modules: set[str] = set()
    for method in contract.methods:
        for ref in (
            method.request,
            method.response,
            method.input_item,
            method.output_item,
        ):
            if ref is not None:
                modules.add(ref.module)
    return sorted(modules)


def _required_type(ref: TypeRef | None, aliases: dict[str, str]) -> str:
    if ref is None:
        raise ValueError("Contract is missing a required type")
    return _render_type(ref, aliases)


def _render_type(ref: TypeRef, aliases: dict[str, str]) -> str:
    return f"{aliases[ref.module]}.{ref.qualname}"
