from __future__ import annotations

import keyword
import re
from collections.abc import Mapping
from pathlib import Path
from typing import Any

from meshcall.ir import ServiceContract, StreamKind, TypeRef


def render_portable_python_client(
    contract: ServiceContract,
    *,
    class_name: str | None = None,
    meshcall_requirement: str = "meshcall>=0.1.0",
    pydantic_requirement: str = "pydantic>=2.11",
) -> str:
    _require_unary(contract)
    registry = _TypeRegistry(contract)
    lines = [
        "# Generated by MeshCall from a portable contract. Do not edit manually.",
        (
            "# External dependencies: "
            f"uv add {meshcall_requirement!r} {pydantic_requirement!r}"
        ),
        "from __future__ import annotations",
        "",
        "from typing import Any, Literal",
        "",
        "from pydantic import BaseModel, Field",
        "",
        "from meshcall.client import ClientBase",
        "",
        "",
    ]
    for ref in registry.refs:
        lines.extend(_render_python_models(registry.name(ref), ref.schema_))
        lines.extend(["", ""])

    lines.extend(
        _render_client_class(
            contract,
            registry,
            class_name or portable_python_client_class_name(contract),
        )
    )
    return "\n".join(lines) + "\n"


def render_portable_python_models(contract: ServiceContract) -> str:
    _require_unary(contract)
    registry = _TypeRegistry(contract)
    lines = [
        "# Generated by MeshCall from a portable contract. Do not edit manually.",
        "from __future__ import annotations",
        "",
        "from typing import Any, Literal",
        "",
        "from pydantic import BaseModel, Field",
        "",
        "",
    ]
    for ref in registry.refs:
        lines.extend(_render_python_models(registry.name(ref), ref.schema_))
        lines.extend(["", ""])
    return "\n".join(lines).rstrip() + "\n"


def render_portable_python_client_module(
    contract: ServiceContract,
    *,
    class_name: str | None = None,
    models_import: str = ".models",
) -> str:
    _require_unary(contract)
    registry = _TypeRegistry(contract)
    type_names = ", ".join(registry.name(ref) for ref in registry.refs)
    lines = [
        "# Generated by MeshCall from a portable contract. Do not edit manually.",
        "from __future__ import annotations",
        "",
        "from meshcall.client import ClientBase",
        f"from {models_import} import {type_names}",
        "",
        "",
    ]
    lines.extend(
        _render_client_class(
            contract,
            registry,
            class_name or portable_python_client_class_name(contract),
        )
    )
    return "\n".join(lines) + "\n"


def portable_python_type_names(contract: ServiceContract) -> tuple[str, ...]:
    registry = _TypeRegistry(contract)
    return tuple(registry.name(ref) for ref in registry.refs)


def portable_python_client_class_name(contract: ServiceContract) -> str:
    base = contract.source_qualname.rsplit(".", 1)[-1]
    return f"{_class_name(base, fallback='Service')}Client"


def write_portable_python_client(
    contract: ServiceContract,
    output: str | Path,
    *,
    class_name: str | None = None,
    meshcall_requirement: str = "meshcall>=0.1.0",
    pydantic_requirement: str = "pydantic>=2.11",
) -> Path:
    target = Path(output)
    target.parent.mkdir(parents=True, exist_ok=True)
    temporary = target.with_suffix(f"{target.suffix}.tmp")
    temporary.write_text(
        render_portable_python_client(
            contract,
            class_name=class_name,
            meshcall_requirement=meshcall_requirement,
            pydantic_requirement=pydantic_requirement,
        ),
        encoding="utf-8",
    )
    temporary.replace(target)
    return target


class _TypeRegistry:
    def __init__(self, contract: ServiceContract) -> None:
        refs: dict[tuple[str, str], TypeRef] = {}
        for method in contract.methods:
            for ref in (method.request, method.response):
                if ref is not None:
                    refs.setdefault((ref.module, ref.qualname), ref)
        self.refs = tuple(refs.values())
        counts: dict[str, int] = {}
        self._names: dict[tuple[str, str], str] = {}
        for ref in self.refs:
            base = _class_name(ref.qualname.rsplit(".", 1)[-1], fallback="Payload")
            count = counts.get(base, 0) + 1
            counts[base] = count
            self._names[(ref.module, ref.qualname)] = (
                base if count == 1 else f"{base}{count}"
            )

    def name(self, ref: TypeRef) -> str:
        return self._names[(ref.module, ref.qualname)]


def _render_client_class(
    contract: ServiceContract,
    registry: _TypeRegistry,
    class_name: str,
) -> list[str]:
    lines = [
        f"class {class_name}(ClientBase):",
        f"    service_name = {contract.name!r}",
    ]
    for method in contract.methods:
        request = registry.name(method.request)
        response = registry.name(_required_ref(method.response))
        lines.extend(
            [
                "",
                f"    async def {method.name}(",
                "        self,",
                f"        request: {request},",
                "        *,",
                "        timeout: float | None = None,",
                f"    ) -> {response}:",
                "        return await self._unary(",
                "            self.service_name,",
                f"            {method.name!r},",
                "            request,",
                f"            {response},",
                "            timeout=timeout,",
                "        )",
            ]
        )
    return lines


def _render_python_models(
    root_name: str,
    schema: Mapping[str, Any],
) -> list[str]:
    definitions = schema.get("$defs", {})
    definition_names = {
        key: f"{root_name}{_class_name(key, fallback='Value')}"
        for key in definitions
    }
    lines: list[str] = []
    for key, definition in definitions.items():
        lines.extend(_render_python_model(definition_names[key], definition, definition_names))
        lines.extend(["", ""])
    lines.extend(_render_python_model(root_name, schema, definition_names))
    return lines


def _render_python_model(
    name: str,
    schema: Mapping[str, Any],
    definition_names: Mapping[str, str],
) -> list[str]:
    if schema.get("type") != "object" and "properties" not in schema:
        raise ValueError(f"Portable Python model {name} must use an object schema")
    required = set(schema.get("required", []))
    properties = schema.get("properties", {})
    lines = [f"class {name}(BaseModel):"]
    if not properties:
        lines.append("    pass")
        return lines
    for property_name, property_schema in properties.items():
        field_name = _field_name(property_name)
        field_type = _python_type(property_schema, definition_names)
        is_required = property_name in required
        if not is_required:
            field_type = f"{field_type} | None"
        default = "" if is_required else " = None"
        if field_name != property_name:
            field_options = f"alias={property_name!r}"
            default_value = "..." if is_required else "None"
            default = f" = Field({default_value}, {field_options})"
        lines.append(f"    {field_name}: {field_type}{default}")
    return lines


def _python_type(
    schema: Mapping[str, Any],
    definition_names: Mapping[str, str],
) -> str:
    reference = schema.get("$ref")
    if isinstance(reference, str) and reference.startswith("#/$defs/"):
        key = reference.rsplit("/", 1)[-1]
        return definition_names.get(key, _class_name(key, fallback="Any"))
    if "const" in schema:
        return f"Literal[{schema['const']!r}]"
    enum = schema.get("enum")
    if isinstance(enum, list) and enum:
        values = ", ".join(repr(value) for value in enum)
        return f"Literal[{values}]"
    for keyword_name in ("anyOf", "oneOf"):
        variants = schema.get(keyword_name)
        if isinstance(variants, list) and variants:
            return " | ".join(
                _python_type(variant, definition_names) for variant in variants
            )
    schema_type = schema.get("type")
    if isinstance(schema_type, list):
        return " | ".join(
            _python_type({**schema, "type": item}, definition_names)
            for item in schema_type
        )
    if schema_type == "integer":
        return "int"
    if schema_type == "number":
        return "float"
    if schema_type == "string":
        return "str"
    if schema_type == "boolean":
        return "bool"
    if schema_type == "null":
        return "None"
    if schema_type == "array":
        return f"list[{_python_type(schema.get('items', {}), definition_names)}]"
    if schema_type == "object":
        additional = schema.get("additionalProperties", {})
        value_type = (
            _python_type(additional, definition_names)
            if isinstance(additional, Mapping)
            else "Any"
        )
        return f"dict[str, {value_type}]"
    return "Any"


def _field_name(value: str) -> str:
    identifier = re.sub(r"\W", "_", value)
    if not identifier or identifier[0].isdigit():
        identifier = f"field_{identifier}"
    if keyword.iskeyword(identifier):
        identifier = f"{identifier}_"
    return identifier


def _class_name(value: str, *, fallback: str) -> str:
    identifier = re.sub(r"[^A-Za-z0-9_]", "_", value)
    if not identifier:
        return fallback
    if identifier[0].isdigit():
        return f"Model_{identifier}"
    return identifier


def _required_ref(ref: TypeRef | None) -> TypeRef:
    if ref is None:
        raise ValueError("Unary method is missing a response type")
    return ref


def _require_unary(contract: ServiceContract) -> None:
    unsupported = [
        method.name for method in contract.methods if method.stream is not StreamKind.UNARY
    ]
    if unsupported:
        names = ", ".join(unsupported)
        raise ValueError(
            f"Portable Python generation currently supports unary methods only: {names}"
        )
